import test from 'node:test';
import assert from 'node:assert/strict';
import { attachJevReview, buildJevQuestions, buildJevState, evaluateJevPlan } from '../api/jev-review.mjs';

const plan = { input: { theme: '雨夜城市纪实', style: '纪实', scene: '斑马线', mood: '安静', extra: '高机位俯拍' }, shotList: [{ title: '环境建立镜头', description: '保留人物与环境关系', shotSize: '全身', focalLength: '35mm', angle: '高机位' }], references: [], director: { requestId: 'test-request' } };
test('redacts identity data and local paths', () => { const state = buildJevState({ ...plan, input: { ...plan.input, email: 'hidden@example.com', localPath: 'D:/secret.jpg' } }); assert.equal(state.brief.email, undefined); assert.equal(JSON.stringify(state).includes('D:/secret.jpg'), false); assert.equal(JSON.stringify(state).includes('hidden@example.com'), false); assert.equal(buildJevQuestions(plan).duplicate_risk.type, 'noul'); });
test('redacts identity data and local paths inside allowed text', () => { const state = buildJevState({ ...plan, input: { ...plan.input, extra: '联系 hidden@example.com，素材在 D:/private/portrait.jpg' }, shotList: [{ description: '读取 C:/Users/user/secret.jpg' }] }); const serialized = JSON.stringify(state); assert.equal(serialized.includes('hidden@example.com'), false); assert.equal(serialized.includes('D:/private'), false); assert.equal(serialized.includes('C:/Users'), false); });
test('maps a valid response', async () => { const env = { AI: { run: async () => ({ model: 'jev-test', answers: { brief_sufficient: { noul: 0.95 }, shot_sequence_quality: { score: 2, confidence: 0.9 }, execution_feasibility: { score: 2, confidence: 0.9 }, duplicate_risk: { noul: 0.1 } } }) } }; const result = await evaluateJevPlan(plan, env); assert.equal(result.status, 'ok'); assert.equal(result.verdict, 'ready'); });
test('maps middle scores to confirmation', async () => { const env = { AI: { run: async () => ({ answers: { brief_sufficient: { noul: 0.95 }, shot_sequence_quality: { score: 1, confidence: 0.9 }, execution_feasibility: { score: 1, confidence: 0.9 }, duplicate_risk: { noul: 0.1 } } }) } }; const result = await evaluateJevPlan(plan, env); assert.equal(result.status, 'ok'); assert.equal(result.verdict, 'confirm'); });
test('fails open and preserves plan', async () => { const result = await attachJevReview(plan, {}); assert.equal(result.director.requestId, 'test-request'); assert.equal(result.director.jevReview.status, 'unavailable'); assert.equal(result.shotList.length, 1); });
test('fails open on malformed response', async () => { const result = await evaluateJevPlan(plan, { AI: { run: async () => ({}) } }); assert.equal(result.status, 'unavailable'); });
test('fails open on incomplete response', async () => { const result = await evaluateJevPlan(plan, { AI: { run: async () => ({ answers: { brief_sufficient: { noul: 0.95 } } }) } }); assert.equal(result.status, 'unavailable'); assert.equal(result.reason, 'invalid_response'); });
test('classifies provider errors without exposing details', async () => { const result = await evaluateJevPlan(plan, { AI: { run: async () => { throw new Error('Model is unavailable for this account'); } } }); assert.equal(result.reason, 'ai_model_unavailable'); assert.equal(JSON.stringify(result).includes('this account'), false); });
